#!/usr/bin/env python3
"""Local HTTP adapter for the Kimi-VL low-RAM runtime.

This is intentionally a thin compatibility layer around the validated one-shot
C generators. Requests are serialized so two HTTP clients cannot accidentally
launch two multi-GiB inference processes at once.

Supported contracts:
- Anthropic Messages API: POST /v1/messages
- Anthropic token count:  POST /v1/messages/count_tokens
- OpenAI chat:            POST /v1/chat/completions
- OpenAI model discovery: GET  /v1/models
- Health:                 GET  /healthz

The first API revision is text-only. Native tool_use/tool_result generation and
image blocks are deliberately not advertised yet. The URLs are stable so the
backend can later switch to a persistent C engine without changing clients.
"""
from __future__ import annotations

import argparse
import codecs
import json
import os
import subprocess
import sys
import tempfile
import threading
import time
import uuid
from dataclasses import dataclass
from http import HTTPStatus
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from typing import Any, Callable

from kimi_tokenizer import build_encoding
from kvl_memory_plan import (
    MIB,
    as_mib,
    parse_trunk_cache_request,
    planned_text_breakdown,
    resolve_trunk_cache_mib,
)

EOS_ID = 163585
IM_END_ID = 163586
STOP_IDS = {EOS_ID, IM_END_ID}
DEFAULT_MODEL_ID = "kimi-vl-a3b-instruct-q8"
DEFAULT_SYSTEM = "You are a helpful assistant"
MAX_REQUEST_BYTES = 16 * 1024 * 1024


def _exe(name: str) -> str:
    if os.name == "nt":
        release = Path("build") / "Release" / f"{name}.exe"
        return str(release if release.exists() else Path("build") / f"{name}.exe")
    return str(Path("build") / name)


def _flatten_text_content(content: Any) -> str:
    """Flatten text-like Anthropic/OpenAI content blocks.

    Tool history is preserved as readable text so a stateless multi-turn request
    does not silently discard previous tool results. New native tool calls are
    not generated by this adapter revision.
    """
    if content is None:
        return ""
    if isinstance(content, str):
        return content
    if not isinstance(content, list):
        raise ValueError("message content must be a string or a list of content blocks")

    parts: list[str] = []
    for block in content:
        if isinstance(block, str):
            parts.append(block)
            continue
        if not isinstance(block, dict):
            raise ValueError("content block must be an object")
        kind = block.get("type", "text")
        if kind in ("text", "input_text", "output_text"):
            parts.append(str(block.get("text", "")))
        elif kind == "tool_result":
            body = _flatten_text_content(block.get("content", ""))
            tool_id = block.get("tool_use_id", "")
            parts.append(f"[tool_result {tool_id}]\n{body}".strip())
        elif kind == "tool_use":
            name = str(block.get("name", "tool"))
            payload = json.dumps(block.get("input", {}), ensure_ascii=False, separators=(",", ":"))
            parts.append(f"[tool_use {name}] {payload}")
        elif kind in ("image", "image_url", "input_image"):
            raise ValueError("image content is not enabled in this API revision; use text for the first smoke test")
        else:
            # Unknown non-text blocks should fail closed instead of disappearing
            # from the prompt and changing semantics invisibly.
            raise ValueError(f"unsupported content block type: {kind}")
    return "\n".join(part for part in parts if part)


def _flatten_system(system: Any) -> str:
    if system is None:
        return DEFAULT_SYSTEM
    text = _flatten_text_content(system)
    return text or DEFAULT_SYSTEM


def _tool_note(tools: Any) -> str:
    if not tools:
        return ""
    if not isinstance(tools, list):
        return "\n\nLocal adapter note: native tool use is unavailable; answer in plain text."
    names: list[str] = []
    for tool in tools:
        if isinstance(tool, dict) and tool.get("name"):
            names.append(str(tool["name"]))
    suffix = f" Tools supplied by the client: {', '.join(names[:32])}." if names else ""
    return (
        "\n\nLocal adapter note: native Anthropic/OpenAI tool calls are not implemented yet. "
        "Do not claim that you executed tools; answer in plain text only." + suffix
    )


def _format_dialogue(messages: Any, system: Any = None, tools: Any = None) -> str:
    if not isinstance(messages, list) or not messages:
        raise ValueError("messages must be a non-empty array")

    system_parts = [_flatten_system(system)]
    turns: list[tuple[str, str]] = []
    for msg in messages:
        if not isinstance(msg, dict):
            raise ValueError("each message must be an object")
        role = str(msg.get("role", ""))
        content = _flatten_text_content(msg.get("content", ""))
        if role in ("system", "developer"):
            if content:
                system_parts.append(content)
            continue
        if role not in ("user", "assistant"):
            raise ValueError(f"unsupported message role: {role}")
        turns.append((role, content))

    if not turns:
        raise ValueError("messages contain no user/assistant turn")
    if turns[-1][0] != "user":
        raise ValueError("this API revision requires the last conversational role to be user")

    system_text = "\n\n".join(part for part in system_parts if part) + _tool_note(tools)
    out = [f"<|im_system|>system<|im_middle|>{system_text}<|im_end|>"]
    for role, content in turns:
        if role == "user":
            out.append(f"<|im_user|>user<|im_middle|>{content}<|im_end|>")
        else:
            out.append(f"<|im_assistant|>assistant<|im_middle|>{content}<|im_end|>")
    out.append("<|im_assistant|>assistant<|im_middle|>")
    return "".join(out)


@dataclass(frozen=True)
class PreparedPrompt:
    ids: list[int]

    @property
    def input_tokens(self) -> int:
        return len(self.ids)


@dataclass(frozen=True)
class GenerationResult:
    text: str
    output_tokens: int
    stopped_by_eos: bool

    @property
    def anthropic_stop_reason(self) -> str:
        return "end_turn" if self.stopped_by_eos else "max_tokens"

    @property
    def openai_finish_reason(self) -> str:
        return "stop" if self.stopped_by_eos else "length"


class KimiRuntime:
    def __init__(
        self,
        model_dir: str | Path,
        binary: str,
        cache_mib: int,
        trunk_cache_mib: str | int,
        ram_mib: int,
        model_id: str,
    ) -> None:
        self.model = Path(model_dir)
        self.binary = str(binary)
        self.cache_mib = int(cache_mib)
        self.trunk_cache_request = trunk_cache_mib
        self.ram_mib = int(ram_mib)
        self.model_id = model_id
        self.lock = threading.Lock()

        if self.cache_mib <= 0 or self.ram_mib <= 0:
            raise ValueError("cache_mib and ram_mib must be positive")
        parse_trunk_cache_request(self.trunk_cache_request)

        required = [
            "trunk.bin",
            "trunk.idx",
            "experts.bin",
            "experts.idx",
            "tiktoken.model",
            "tokenizer_config.json",
        ]
        missing = [name for name in required if not (self.model / name).is_file()]
        if missing:
            raise FileNotFoundError("missing runtime files: " + ", ".join(missing))
        if not Path(self.binary).is_file():
            raise FileNotFoundError(f"generator binary not found: {self.binary}")

        self.enc, _, _ = build_encoding(self.model)

    def prepare(self, messages: Any, system: Any = None, tools: Any = None) -> PreparedPrompt:
        formatted = _format_dialogue(messages, system, tools)
        return PreparedPrompt(self.enc.encode(formatted, allowed_special="all"))

    def _plan(self, prompt_tokens: int, max_tokens: int) -> tuple[int, dict[str, int]]:
        if max_tokens <= 0:
            raise ValueError("max_tokens must be positive")
        trunk_cache_mib = resolve_trunk_cache_mib(
            prompt_tokens,
            max_tokens,
            self.cache_mib,
            self.ram_mib,
            self.trunk_cache_request,
        )
        plan = planned_text_breakdown(prompt_tokens, max_tokens, self.cache_mib, trunk_cache_mib)
        budget = self.ram_mib * MIB
        if plan["total"] > budget:
            raise ValueError(
                f"RAM plan rejected: {as_mib(plan['total']):.1f} MiB > {self.ram_mib} MiB; "
                "reduce context/max_tokens/cache or raise --ram-mib"
            )
        return trunk_cache_mib, plan

    def preflight(self, prepared: PreparedPrompt, max_tokens: int, temperature: float) -> None:
        if temperature < 0:
            raise ValueError("temperature must be >= 0")
        self._plan(prepared.input_tokens, max_tokens)

    def generate(
        self,
        prepared: PreparedPrompt,
        max_tokens: int,
        temperature: float,
        seed: int,
        on_delta: Callable[[str], None] | None = None,
    ) -> GenerationResult:
        if temperature < 0:
            raise ValueError("temperature must be >= 0")
        trunk_cache_mib, plan = self._plan(prepared.input_tokens, max_tokens)

        with self.lock:
            with tempfile.NamedTemporaryFile("w", encoding="ascii", delete=False, suffix=".ids") as fh:
                ids_path = Path(fh.name)
                fh.write("\n".join(map(str, prepared.ids)))
                fh.write("\n")

            cmd = [
                self.binary,
                str(self.model / "trunk.bin"),
                str(self.model / "trunk.idx"),
                str(self.model / "experts.bin"),
                str(self.model / "experts.idx"),
                str(ids_path),
                str(self.cache_mib * MIB),
                str(max_tokens),
                str(temperature),
                str(seed),
            ]
            env = os.environ.copy()
            env["KVL_TRUNK_CACHE_MIB"] = str(trunk_cache_mib)

            print(
                f"[kvl-api] request prompt={prepared.input_tokens} max_tokens={max_tokens} "
                f"cache={self.cache_mib}MiB trunk_cache={trunk_cache_mib}MiB "
                f"RAM_plan={as_mib(plan['total']):.1f}/{self.ram_mib}MiB",
                file=sys.stderr,
            )

            proc: subprocess.Popen[str] | None = None
            decoder = codecs.getincrementaldecoder("utf-8")("replace")
            text_parts: list[str] = []
            output_tokens = 0
            stopped_by_eos = False
            try:
                proc = subprocess.Popen(
                    cmd,
                    stdout=subprocess.PIPE,
                    text=True,
                    bufsize=1,
                    env=env,
                )
                assert proc.stdout is not None
                for raw in proc.stdout:
                    line = raw.strip()
                    if not line.startswith("TOKEN "):
                        continue
                    token = int(line.split()[1])
                    output_tokens += 1
                    if token in STOP_IDS:
                        stopped_by_eos = True
                        break
                    try:
                        token_bytes = self.enc.decode_single_token_bytes(token)
                        delta = decoder.decode(token_bytes, final=False)
                    except KeyError:
                        delta = self.enc.decode([token])
                    if delta:
                        text_parts.append(delta)
                        if on_delta is not None:
                            on_delta(delta)

                # The C process normally exits immediately after EOS/max_new. If we
                # stopped reading on EOS, keep draining stdout so wait() cannot block
                # on a full pipe in future more-verbose binaries.
                if proc.stdout is not None:
                    for _ in proc.stdout:
                        pass
                rc = proc.wait()
                if rc != 0:
                    raise RuntimeError(f"C generator exited with code {rc}")

                tail = decoder.decode(b"", final=True)
                if tail:
                    text_parts.append(tail)
                    if on_delta is not None:
                        on_delta(tail)
            except BaseException:
                if proc is not None and proc.poll() is None:
                    proc.terminate()
                    try:
                        proc.wait(timeout=3)
                    except subprocess.TimeoutExpired:
                        proc.kill()
                raise
            finally:
                try:
                    ids_path.unlink()
                except OSError:
                    pass

        return GenerationResult("".join(text_parts), output_tokens, stopped_by_eos)


def _message_id(prefix: str) -> str:
    return f"{prefix}_{uuid.uuid4().hex[:24]}"


def _anthropic_response(
    model: str,
    prepared: PreparedPrompt,
    result: GenerationResult,
    message_id: str | None = None,
) -> dict[str, Any]:
    return {
        "id": message_id or _message_id("msg"),
        "type": "message",
        "role": "assistant",
        "model": model,
        "content": [{"type": "text", "text": result.text}],
        "stop_reason": result.anthropic_stop_reason,
        "stop_sequence": None,
        "usage": {
            "input_tokens": prepared.input_tokens,
            "output_tokens": result.output_tokens,
        },
    }


def _openai_response(
    model: str,
    prepared: PreparedPrompt,
    result: GenerationResult,
    completion_id: str | None = None,
) -> dict[str, Any]:
    now = int(time.time())
    return {
        "id": completion_id or _message_id("chatcmpl"),
        "object": "chat.completion",
        "created": now,
        "model": model,
        "choices": [
            {
                "index": 0,
                "message": {"role": "assistant", "content": result.text},
                "finish_reason": result.openai_finish_reason,
            }
        ],
        "usage": {
            "prompt_tokens": prepared.input_tokens,
            "completion_tokens": result.output_tokens,
            "total_tokens": prepared.input_tokens + result.output_tokens,
        },
    }


class KimiHTTPServer(ThreadingHTTPServer):
    daemon_threads = True

    def __init__(
        self,
        address: tuple[str, int],
        runtime: Any,
        model_id: str,
        api_key: str | None,
    ) -> None:
        self.runtime = runtime
        self.model_id = model_id
        self.api_key = api_key
        super().__init__(address, KimiRequestHandler)


class KimiRequestHandler(BaseHTTPRequestHandler):
    server: KimiHTTPServer
    protocol_version = "HTTP/1.1"

    def log_message(self, fmt: str, *args: Any) -> None:
        sys.stderr.write("[kvl-api] " + (fmt % args) + "\n")

    def _cors(self) -> None:
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header(
            "Access-Control-Allow-Headers",
            "authorization, content-type, x-api-key, anthropic-version, anthropic-beta",
        )
        self.send_header("Access-Control-Allow-Methods", "GET, POST, OPTIONS")

    def _json(self, status: int, payload: dict[str, Any]) -> None:
        body = json.dumps(payload, ensure_ascii=False, separators=(",", ":")).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self._cors()
        self.end_headers()
        self.wfile.write(body)

    def _authorized(self) -> bool:
        expected = self.server.api_key
        if not expected:
            return True
        xkey = self.headers.get("x-api-key")
        bearer = self.headers.get("authorization", "")
        if xkey == expected or bearer == f"Bearer {expected}":
            return True
        self._json(
            HTTPStatus.UNAUTHORIZED,
            {
                "type": "error",
                "error": {"type": "authentication_error", "message": "invalid local API key"},
            },
        )
        return False

    def _read_json(self) -> dict[str, Any]:
        raw_len = self.headers.get("content-length")
        if raw_len is None:
            raise ValueError("missing Content-Length")
        length = int(raw_len)
        if length < 0 or length > MAX_REQUEST_BYTES:
            raise ValueError(f"request body too large (limit {MAX_REQUEST_BYTES} bytes)")
        raw = self.rfile.read(length)
        data = json.loads(raw.decode("utf-8"))
        if not isinstance(data, dict):
            raise ValueError("JSON body must be an object")
        return data

    def _validate_model(self, body: dict[str, Any]) -> None:
        requested = body.get("model", self.server.model_id)
        if requested != self.server.model_id:
            raise ValueError(f"unknown model '{requested}'; configured model is '{self.server.model_id}'")

    def do_OPTIONS(self) -> None:
        self.send_response(HTTPStatus.NO_CONTENT)
        self._cors()
        self.send_header("Content-Length", "0")
        self.end_headers()

    def do_GET(self) -> None:
        if not self._authorized():
            return
        path = self.path.split("?", 1)[0]
        if path == "/healthz":
            busy = bool(getattr(self.server.runtime.lock, "locked", lambda: False)())
            self._json(
                HTTPStatus.OK,
                {
                    "status": "ok",
                    "model": self.server.model_id,
                    "backend": "serialized-process-v1",
                    "busy": busy,
                },
            )
            return
        if path == "/v1/models":
            self._json(
                HTTPStatus.OK,
                {
                    "object": "list",
                    "data": [
                        {
                            "id": self.server.model_id,
                            "object": "model",
                            "created": 0,
                            "owned_by": "local-kimi",
                        }
                    ],
                },
            )
            return
        self._json(HTTPStatus.NOT_FOUND, {"error": {"message": "not found", "type": "not_found"}})

    def do_POST(self) -> None:
        if not self._authorized():
            return
        try:
            body = self._read_json()
            path = self.path.split("?", 1)[0]
            if path == "/v1/messages":
                self._anthropic_messages(body)
            elif path == "/v1/messages/count_tokens":
                self._anthropic_count(body)
            elif path == "/v1/chat/completions":
                self._openai_chat(body)
            else:
                self._json(HTTPStatus.NOT_FOUND, {"error": {"message": "not found", "type": "not_found"}})
        except (BrokenPipeError, ConnectionResetError):
            self.log_message("client disconnected")
        except (ValueError, json.JSONDecodeError) as exc:
            self._safe_error(HTTPStatus.BAD_REQUEST, "invalid_request_error", str(exc))
        except FileNotFoundError as exc:
            self._safe_error(HTTPStatus.INTERNAL_SERVER_ERROR, "backend_error", str(exc))
        except Exception as exc:
            self.log_message("backend error: %r", exc)
            self._safe_error(HTTPStatus.INTERNAL_SERVER_ERROR, "backend_error", str(exc))

    def _safe_error(self, status: int, kind: str, message: str) -> None:
        try:
            self._json(status, {"type": "error", "error": {"type": kind, "message": message}})
        except (BrokenPipeError, ConnectionResetError):
            pass

    def _anthropic_count(self, body: dict[str, Any]) -> None:
        self._validate_model(body)
        prepared = self.server.runtime.prepare(
            body.get("messages"),
            body.get("system"),
            body.get("tools"),
        )
        self._json(HTTPStatus.OK, {"input_tokens": prepared.input_tokens})

    def _anthropic_messages(self, body: dict[str, Any]) -> None:
        self._validate_model(body)
        prepared = self.server.runtime.prepare(
            body.get("messages"),
            body.get("system"),
            body.get("tools"),
        )
        max_tokens = int(body.get("max_tokens", 128))
        temperature = float(body.get("temperature", 0.2))
        seed = int(body.get("seed", 1))
        if body.get("stream", False):
            self.server.runtime.preflight(prepared, max_tokens, temperature)
            self._anthropic_stream(prepared, max_tokens, temperature, seed)
            return
        result = self.server.runtime.generate(prepared, max_tokens, temperature, seed)
        self._json(HTTPStatus.OK, _anthropic_response(self.server.model_id, prepared, result))

    def _anthropic_stream(
        self,
        prepared: PreparedPrompt,
        max_tokens: int,
        temperature: float,
        seed: int,
    ) -> None:
        message_id = _message_id("msg")
        self.send_response(HTTPStatus.OK)
        self.send_header("Content-Type", "text/event-stream; charset=utf-8")
        self.send_header("Cache-Control", "no-cache")
        self.send_header("Connection", "close")
        self._cors()
        self.end_headers()
        self.close_connection = True

        def send_event(event: str, data: dict[str, Any]) -> None:
            payload = json.dumps(data, ensure_ascii=False, separators=(",", ":"))
            self.wfile.write(f"event: {event}\ndata: {payload}\n\n".encode("utf-8"))
            self.wfile.flush()

        send_event(
            "message_start",
            {
                "type": "message_start",
                "message": {
                    "id": message_id,
                    "type": "message",
                    "role": "assistant",
                    "model": self.server.model_id,
                    "content": [],
                    "stop_reason": None,
                    "stop_sequence": None,
                    "usage": {"input_tokens": prepared.input_tokens, "output_tokens": 0},
                },
            },
        )
        send_event(
            "content_block_start",
            {
                "type": "content_block_start",
                "index": 0,
                "content_block": {"type": "text", "text": ""},
            },
        )

        def on_delta(delta: str) -> None:
            send_event(
                "content_block_delta",
                {
                    "type": "content_block_delta",
                    "index": 0,
                    "delta": {"type": "text_delta", "text": delta},
                },
            )

        result = self.server.runtime.generate(prepared, max_tokens, temperature, seed, on_delta)
        send_event("content_block_stop", {"type": "content_block_stop", "index": 0})
        send_event(
            "message_delta",
            {
                "type": "message_delta",
                "delta": {"stop_reason": result.anthropic_stop_reason, "stop_sequence": None},
                "usage": {"output_tokens": result.output_tokens},
            },
        )
        send_event("message_stop", {"type": "message_stop"})

    def _openai_chat(self, body: dict[str, Any]) -> None:
        self._validate_model(body)
        prepared = self.server.runtime.prepare(
            body.get("messages"),
            None,
            body.get("tools"),
        )
        max_tokens = int(body.get("max_tokens", body.get("max_completion_tokens", 128)))
        temperature = float(body.get("temperature", 0.2))
        seed = int(body.get("seed", 1))
        if body.get("stream", False):
            self.server.runtime.preflight(prepared, max_tokens, temperature)
            self._openai_stream(prepared, max_tokens, temperature, seed)
            return
        result = self.server.runtime.generate(prepared, max_tokens, temperature, seed)
        self._json(HTTPStatus.OK, _openai_response(self.server.model_id, prepared, result))

    def _openai_stream(
        self,
        prepared: PreparedPrompt,
        max_tokens: int,
        temperature: float,
        seed: int,
    ) -> None:
        completion_id = _message_id("chatcmpl")
        created = int(time.time())
        self.send_response(HTTPStatus.OK)
        self.send_header("Content-Type", "text/event-stream; charset=utf-8")
        self.send_header("Cache-Control", "no-cache")
        self.send_header("Connection", "close")
        self._cors()
        self.end_headers()
        self.close_connection = True

        def send_chunk(delta: dict[str, Any], finish_reason: str | None = None) -> None:
            payload = {
                "id": completion_id,
                "object": "chat.completion.chunk",
                "created": created,
                "model": self.server.model_id,
                "choices": [
                    {
                        "index": 0,
                        "delta": delta,
                        "finish_reason": finish_reason,
                    }
                ],
            }
            raw = json.dumps(payload, ensure_ascii=False, separators=(",", ":"))
            self.wfile.write(f"data: {raw}\n\n".encode("utf-8"))
            self.wfile.flush()

        send_chunk({"role": "assistant", "content": ""})

        def on_delta(delta: str) -> None:
            send_chunk({"content": delta})

        result = self.server.runtime.generate(prepared, max_tokens, temperature, seed, on_delta)
        send_chunk({}, result.openai_finish_reason)
        self.wfile.write(b"data: [DONE]\n\n")
        self.wfile.flush()


def build_arg_parser() -> argparse.ArgumentParser:
    ap = argparse.ArgumentParser(
        description="Serve Kimi-VL low-RAM runtime over local Anthropic/OpenAI HTTP APIs"
    )
    ap.add_argument("model_dir", help="packed runtime directory")
    ap.add_argument("--host", default="127.0.0.1")
    ap.add_argument("--port", type=int, default=8000)
    ap.add_argument("--model-id", default=DEFAULT_MODEL_ID)
    ap.add_argument("--api-key", default="local-kimi", help="local key; empty string disables auth")
    ap.add_argument("--binary", default=_exe("kvl_generate"))
    ap.add_argument("--cache-mib", type=int, default=512)
    ap.add_argument("--trunk-cache-mib", default="auto")
    ap.add_argument("--ram-mib", type=int, default=4096)
    return ap


def main() -> int:
    args = build_arg_parser().parse_args()
    runtime = KimiRuntime(
        args.model_dir,
        args.binary,
        args.cache_mib,
        args.trunk_cache_mib,
        args.ram_mib,
        args.model_id,
    )
    server = KimiHTTPServer((args.host, args.port), runtime, args.model_id, args.api_key or None)
    print(
        f"[kvl-api] serving model={args.model_id} at http://{args.host}:{args.port} "
        f"(Anthropic base=http://{args.host}:{args.port}, OpenAI base=http://{args.host}:{args.port}/v1)",
        file=sys.stderr,
    )
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        pass
    finally:
        server.server_close()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
